name: Main
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Generated SDK version'
        required: false
        default: ''
      name:
        description: 'Generated SDK name'
        required: true
      fileAsBase64:
        description: 'Generated SDK file as base64 encoded'
        required: true
      test:
        description: 'Release snapshot?'
        required: false
jobs:
  prepare_version:
    uses: ./.github/workflows/prepare_version.yml
    with:
      version: ${{ github.event.inputs.version }}
      name: ${{ github.event.inputs.name }}
  generate:
    needs: [ prepare_version ]
    uses: ./.github/workflows/generate.yml
    with:
      version: ${{ needs.prepare_version.outputs.version }}
      name: ${{ github.event.inputs.name }}
      fileAsBase64: ${{ github.event.inputs.fileAsBase64 }}
  publish:
    needs: [ generate ]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      test: ${{ github.event.inputs.test }}
