/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.expediagroup.openworld.sdk.fraudprevention.models

import com.expediagroup.openworld.sdk.fraudprevention.models.Amount
import com.expediagroup.openworld.sdk.fraudprevention.models.Name
import com.expediagroup.openworld.sdk.fraudprevention.models.Operations
import com.expediagroup.openworld.sdk.fraudprevention.models.PaymentBillingAddress
import com.expediagroup.openworld.sdk.fraudprevention.models.PaymentMethod
import com.expediagroup.openworld.sdk.fraudprevention.models.PaymentReason
import com.expediagroup.openworld.sdk.fraudprevention.models.PaymentThreeDSCriteria

import com.fasterxml.jackson.annotation.JsonProperty
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.Length;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonSubTypes.Type
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * The `method` field value is used as a discriminator, with the following mapping: * `CREDIT_CARD`: `CreditCard` * `PAYPAL`: `PayPal` * `POINTS`: `Points` 
 * @param brand The `brand` field value is the payment brand used for payment on this transaction. For credit card payment method ensure attributes mentioned in dictionary below are set to corresponding values only. Ensure to comply with the naming standards provided in below dictionary. For example, some Payment processors use “Japan Credit Bureau” but “JCB” should be used when calling Fraud API. Incorrect `brand` - `card_type` combination will result in data quality issues and result in degraded risk recommendation. 'brand' is an enum value with the following mapping with CreditCard 'card_type' attribute: *       brand                 :      card_type * ------------------------------------------------------- * `AMERICAN_EXPRESS`          : `AMERICAN_EXPRESS` * `DINERS_CLUB_INTERNATIONAL` : `DINERS_CLUB` * `BC_CARD`                   : `DINERS_CLUB` * `DISCOVER`                  : `DISCOVER` * `BC_CARD`                   : `DISCOVER` * `DINERS_CLUB_INTERNATIONAL` : `DISCOVER` * `JCB`                       : `DISCOVER` * `JCB`                       : `JCB` * `MASTER_CARD`               : `MASTER_CARD` * `MAESTRO`                   : `MASTER_CARD` * `POSTEPAY_MASTERCARD`       : `MASTER_CARD` * `SOLO`                      : `SOLO` * `SWITCH`                    : `SWITCH` * `MAESTRO`                   : `MAESTRO` * `CHINA_UNION_PAY`           : `CHINA_UNION_PAY` * `VISA`                      : `VISA` * `VISA_DELTA`                : `VISA` * `VISA_ELECTRON`             : `VISA` * `CARTA_SI`                  : `VISA` * `CARTE_BLEUE`               : `VISA` * `VISA_DANKORT`              : `VISA` * `POSTEPAY_VISA_ELECTRON`    : `VISA` * `PAYPAL`                    : 
 * @param method 
 * @param billingName 
 * @param billingAddress 
 * @param billingEmailAddress Email address associated with the payment.
 * @param reason 
 * @param authorizedAmount 
 * @param verifiedAmount 
 * @param threeDigitsSecureCriteria 
 * @param operations 
 */
@JsonIgnoreProperties(ignoreUnknown = true, value = ["method"])
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "method", visible = true)
@JsonSubTypes(
    Type(value = CreditCard::class, name = "CREDIT_CARD"),
    Type(value = PayPal::class, name = "PAYPAL"),
    Type(value = Points::class, name = "POINTS")
)
interface Payment {


        /* The `brand` field value is the payment brand used for payment on this transaction. For credit card payment method ensure attributes mentioned in dictionary below are set to corresponding values only. Ensure to comply with the naming standards provided in below dictionary. For example, some Payment processors use “Japan Credit Bureau” but “JCB” should be used when calling Fraud API. Incorrect `brand` - `card_type` combination will result in data quality issues and result in degraded risk recommendation. 'brand' is an enum value with the following mapping with CreditCard 'card_type' attribute: *       brand                 :      card_type * ------------------------------------------------------- * `AMERICAN_EXPRESS`          : `AMERICAN_EXPRESS` * `DINERS_CLUB_INTERNATIONAL` : `DINERS_CLUB` * `BC_CARD`                   : `DINERS_CLUB` * `DISCOVER`                  : `DISCOVER` * `BC_CARD`                   : `DISCOVER` * `DINERS_CLUB_INTERNATIONAL` : `DISCOVER` * `JCB`                       : `DISCOVER` * `JCB`                       : `JCB` * `MASTER_CARD`               : `MASTER_CARD` * `MAESTRO`                   : `MASTER_CARD` * `POSTEPAY_MASTERCARD`       : `MASTER_CARD` * `SOLO`                      : `SOLO` * `SWITCH`                    : `SWITCH` * `MAESTRO`                   : `MAESTRO` * `CHINA_UNION_PAY`           : `CHINA_UNION_PAY` * `VISA`                      : `VISA` * `VISA_DELTA`                : `VISA` * `VISA_ELECTRON`             : `VISA` * `CARTA_SI`                  : `VISA` * `CARTE_BLEUE`               : `VISA` * `VISA_DANKORT`              : `VISA` * `POSTEPAY_VISA_ELECTRON`    : `VISA` * `PAYPAL`                    :  */

val brand: Payment.Brand
    
val method: PaymentMethod
    
val billingName: Name
    
val billingAddress: PaymentBillingAddress
        /* Email address associated with the payment. */

val billingEmailAddress: kotlin.String
    val reason: PaymentReason?
    val authorizedAmount: Amount?
    val verifiedAmount: Amount?
    val threeDigitsSecureCriteria: PaymentThreeDSCriteria?
    val operations: Operations?

    /**
     * The `brand` field value is the payment brand used for payment on this transaction. For credit card payment method ensure attributes mentioned in dictionary below are set to corresponding values only. Ensure to comply with the naming standards provided in below dictionary. For example, some Payment processors use “Japan Credit Bureau” but “JCB” should be used when calling Fraud API. Incorrect `brand` - `card_type` combination will result in data quality issues and result in degraded risk recommendation. 'brand' is an enum value with the following mapping with CreditCard 'card_type' attribute: *       brand                 :      card_type * ------------------------------------------------------- * `AMERICAN_EXPRESS`          : `AMERICAN_EXPRESS` * `DINERS_CLUB_INTERNATIONAL` : `DINERS_CLUB` * `BC_CARD`                   : `DINERS_CLUB` * `DISCOVER`                  : `DISCOVER` * `BC_CARD`                   : `DISCOVER` * `DINERS_CLUB_INTERNATIONAL` : `DISCOVER` * `JCB`                       : `DISCOVER` * `JCB`                       : `JCB` * `MASTER_CARD`               : `MASTER_CARD` * `MAESTRO`                   : `MASTER_CARD` * `POSTEPAY_MASTERCARD`       : `MASTER_CARD` * `SOLO`                      : `SOLO` * `SWITCH`                    : `SWITCH` * `MAESTRO`                   : `MAESTRO` * `CHINA_UNION_PAY`           : `CHINA_UNION_PAY` * `VISA`                      : `VISA` * `VISA_DELTA`                : `VISA` * `VISA_ELECTRON`             : `VISA` * `CARTA_SI`                  : `VISA` * `CARTE_BLEUE`               : `VISA` * `VISA_DANKORT`              : `VISA` * `POSTEPAY_VISA_ELECTRON`    : `VISA` * `PAYPAL`                    : 
     * Values: AMERICAN_EXPRESS,DINERS_CLUB_INTERNATIONAL,BC_CARD,DISCOVER,JCB,MASTER_CARD,MAESTRO,POSTEPAY_MASTERCARD,SOLO,SWITCH,CHINA_UNION_PAY,VISA,VISA_DELTA,VISA_ELECTRON,CARTA_SI,CARTE_BLEUE,VISA_DANKORT,POSTEPAY_VISA_ELECTRON,PAYPAL
     */
    enum class Brand(val value: kotlin.String) {
        @JsonProperty("AMERICAN_EXPRESS")
        AMERICAN_EXPRESS("AMERICAN_EXPRESS"),
        
        @JsonProperty("DINERS_CLUB_INTERNATIONAL")
        DINERS_CLUB_INTERNATIONAL("DINERS_CLUB_INTERNATIONAL"),
        
        @JsonProperty("BC_CARD")
        BC_CARD("BC_CARD"),
        
        @JsonProperty("DISCOVER")
        DISCOVER("DISCOVER"),
        
        @JsonProperty("JCB")
        JCB("JCB"),
        
        @JsonProperty("MASTER_CARD")
        MASTER_CARD("MASTER_CARD"),
        
        @JsonProperty("MAESTRO")
        MAESTRO("MAESTRO"),
        
        @JsonProperty("POSTEPAY_MASTERCARD")
        POSTEPAY_MASTERCARD("POSTEPAY_MASTERCARD"),
        
        @JsonProperty("SOLO")
        SOLO("SOLO"),
        
        @JsonProperty("SWITCH")
        SWITCH("SWITCH"),
        
        @JsonProperty("CHINA_UNION_PAY")
        CHINA_UNION_PAY("CHINA_UNION_PAY"),
        
        @JsonProperty("VISA")
        VISA("VISA"),
        
        @JsonProperty("VISA_DELTA")
        VISA_DELTA("VISA_DELTA"),
        
        @JsonProperty("VISA_ELECTRON")
        VISA_ELECTRON("VISA_ELECTRON"),
        
        @JsonProperty("CARTA_SI")
        CARTA_SI("CARTA_SI"),
        
        @JsonProperty("CARTE_BLEUE")
        CARTE_BLEUE("CARTE_BLEUE"),
        
        @JsonProperty("VISA_DANKORT")
        VISA_DANKORT("VISA_DANKORT"),
        
        @JsonProperty("POSTEPAY_VISA_ELECTRON")
        POSTEPAY_VISA_ELECTRON("POSTEPAY_VISA_ELECTRON"),
        
        @JsonProperty("PAYPAL")
        PAYPAL("PAYPAL");
    }
}

