/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.xap.models

import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * Capacity for car's properties.
 * @param adultCount The typical number of adults that can fit comfortably in the car.
 * @param childCount The typical number of children that can fit comfortably in the car.
 * @param smallLuggageCount The typical number of small pieces of luggage that fit in the cargo space.
 * @param largeLuggageCount The typical number of large pieces of luggage that fit in the cargo space.
 */
data class Capacity(
    // The typical number of adults that can fit comfortably in the car.
    @JsonProperty("AdultCount")
    val adultCount: kotlin.Long,
    // The typical number of children that can fit comfortably in the car.
    @JsonProperty("ChildCount")
    val childCount: kotlin.Long? = null,
    // The typical number of small pieces of luggage that fit in the cargo space.
    @JsonProperty("SmallLuggageCount")
    val smallLuggageCount: kotlin.Long? = null,
    // The typical number of large pieces of luggage that fit in the cargo space.
    @JsonProperty("LargeLuggageCount")
    val largeLuggageCount: kotlin.Long? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var adultCount: kotlin.Long? = null,
        private var childCount: kotlin.Long? = null,
        private var smallLuggageCount: kotlin.Long? = null,
        private var largeLuggageCount: kotlin.Long? = null
    ) {
        fun adultCount(adultCount: kotlin.Long) = apply { this.adultCount = adultCount }

        fun childCount(childCount: kotlin.Long?) = apply { this.childCount = childCount }

        fun smallLuggageCount(smallLuggageCount: kotlin.Long?) = apply { this.smallLuggageCount = smallLuggageCount }

        fun largeLuggageCount(largeLuggageCount: kotlin.Long?) = apply { this.largeLuggageCount = largeLuggageCount }

        fun build(): Capacity {
            // Check required params
            validateNullity()
            return Capacity(
                adultCount = adultCount!!,
                childCount = childCount,
                smallLuggageCount = smallLuggageCount,
                largeLuggageCount = largeLuggageCount
            )
        }

        private fun validateNullity() {
            if (adultCount == null) {
                throw NullPointerException("Required parameter adultCount is missing")
            }
        }
    }

    fun toBuilder() =
        Builder(
            adultCount = adultCount!!,
            childCount = childCount,
            smallLuggageCount = smallLuggageCount,
            largeLuggageCount = largeLuggageCount
        )
}
