/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.xap.models

import com.expediagroup.sdk.xap.models.CarAddress
import com.expediagroup.sdk.xap.models.CarCountry
import com.expediagroup.sdk.xap.models.CarGeoLocation
import com.expediagroup.sdk.xap.models.CarNeighborhood
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * Container for list of possible locations that could be used to disambiguate the query.
 * @param locationId Location id.
 * @param type The type of location code (MULTICITY | METROCODE).
 * @param id Expedia Region ID of the specified airport.
 * @param name Location Name
 * @param code Location Code
 * @param address
 * @param pointOfInterest
 * @param geoLocation
 * @param neighborhood
 * @param regionId RegionId the location resides in.
 * @param country
 */
data class CarLocation(
    // Location id.
    @JsonProperty("LocationId")
    @field:Valid
    val locationId: kotlin.String,
    // The type of location code (MULTICITY | METROCODE).
    @JsonProperty("Type")
    @field:Valid
    val type: kotlin.String? = null,
    // Expedia Region ID of the specified airport.
    @JsonProperty("Id")
    @field:Valid
    val id: kotlin.String? = null,
    // Location Name
    @JsonProperty("Name")
    @field:Valid
    val name: kotlin.String? = null,
    // Location Code
    @JsonProperty("Code")
    @field:Valid
    val code: kotlin.String? = null,
    @JsonProperty("Address")
    @field:Valid
    val address: CarAddress? = null,
    @JsonProperty("PointOfInterest")
    @field:Valid
    val pointOfInterest: kotlin.String? = null,
    @JsonProperty("GeoLocation")
    @field:Valid
    val geoLocation: CarGeoLocation? = null,
    @JsonProperty("Neighborhood")
    @field:Valid
    val neighborhood: CarNeighborhood? = null,
    // RegionId the location resides in.
    @JsonProperty("RegionId")
    val regionId: kotlin.Long? = null,
    @JsonProperty("Country")
    @field:Valid
    val country: CarCountry? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var locationId: kotlin.String? = null,
        private var type: kotlin.String? = null,
        private var id: kotlin.String? = null,
        private var name: kotlin.String? = null,
        private var code: kotlin.String? = null,
        private var address: CarAddress? = null,
        private var pointOfInterest: kotlin.String? = null,
        private var geoLocation: CarGeoLocation? = null,
        private var neighborhood: CarNeighborhood? = null,
        private var regionId: kotlin.Long? = null,
        private var country: CarCountry? = null
    ) {
        fun locationId(locationId: kotlin.String) = apply { this.locationId = locationId }

        fun type(type: kotlin.String?) = apply { this.type = type }

        fun id(id: kotlin.String?) = apply { this.id = id }

        fun name(name: kotlin.String?) = apply { this.name = name }

        fun code(code: kotlin.String?) = apply { this.code = code }

        fun address(address: CarAddress?) = apply { this.address = address }

        fun pointOfInterest(pointOfInterest: kotlin.String?) = apply { this.pointOfInterest = pointOfInterest }

        fun geoLocation(geoLocation: CarGeoLocation?) = apply { this.geoLocation = geoLocation }

        fun neighborhood(neighborhood: CarNeighborhood?) = apply { this.neighborhood = neighborhood }

        fun regionId(regionId: kotlin.Long?) = apply { this.regionId = regionId }

        fun country(country: CarCountry?) = apply { this.country = country }

        fun build(): CarLocation {
            // Check required params
            validateNullity()
            return CarLocation(
                locationId = locationId!!,
                type = type,
                id = id,
                name = name,
                code = code,
                address = address,
                pointOfInterest = pointOfInterest,
                geoLocation = geoLocation,
                neighborhood = neighborhood,
                regionId = regionId,
                country = country
            )
        }

        private fun validateNullity() {
            if (locationId == null) {
                throw NullPointerException("Required parameter locationId is missing")
            }
        }
    }

    fun toBuilder() =
        Builder(
            locationId = locationId!!,
            type = type,
            id = id,
            name = name,
            code = code,
            address = address,
            pointOfInterest = pointOfInterest,
            geoLocation = geoLocation,
            neighborhood = neighborhood,
            regionId = regionId,
            country = country
        )
}
