/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.xap.models

import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * List of discount information.
 * @param type Discount type. Supported values : CorpDiscount | Coupon.
 * @param code Discount code.
 */
data class Discount(
    // Discount type. Supported values : CorpDiscount | Coupon.
    @JsonProperty("Type")
    @field:Valid
    val type: kotlin.String,
    // Discount code.
    @JsonProperty("Code")
    @field:Valid
    val code: kotlin.String
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var type: kotlin.String? = null,
        private var code: kotlin.String? = null
    ) {
        fun type(type: kotlin.String) = apply { this.type = type }

        fun code(code: kotlin.String) = apply { this.code = code }

        fun build(): Discount {
            // Check required params
            validateNullity()
            return Discount(
                type = type!!,
                code = code!!
            )
        }

        private fun validateNullity() {
            if (type == null) {
                throw NullPointerException("Required parameter type is missing")
            }
            if (code == null) {
                throw NullPointerException("Required parameter code is missing")
            }
        }
    }

    fun toBuilder() =
        Builder(
            type = type!!,
            code = code!!
        )
}
