/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.xap.models

import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * The maximum amount of time for a rental that still qualifies for this rate.This may or may not be the same as the current rental duration.
 * @param unit The unit for minimum amount of time for a rental.
 * @param count The minimum number of units that qualify for minimum amount of time for a rental.
 */
data class Duration(
    // The unit for minimum amount of time for a rental.
    @JsonProperty("Unit")
    @field:Valid
    val unit: kotlin.String,
    // The minimum number of units that qualify for minimum amount of time for a rental.
    @JsonProperty("Count")
    val count: kotlin.Long
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var unit: kotlin.String? = null,
        private var count: kotlin.Long? = null
    ) {
        fun unit(unit: kotlin.String) = apply { this.unit = unit }

        fun count(count: kotlin.Long) = apply { this.count = count }

        fun build(): Duration {
            // Check required params
            validateNullity()
            return Duration(
                unit = unit!!,
                count = count!!
            )
        }

        private fun validateNullity() {
            if (unit == null) {
                throw NullPointerException("Required parameter unit is missing")
            }
            if (count == null) {
                throw NullPointerException("Required parameter count is missing")
            }
        }
    }

    fun toBuilder() =
        Builder(
            unit = unit!!,
            count = count!!
        )
}
