/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.xap.models

import com.expediagroup.sdk.xap.models.Duration
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * Limitations that are part of this rental agreement.
 * @param minDuration
 * @param maxDuration
 */
data class RentalLimits(
    @JsonProperty("MinDuration")
    @field:Valid
    val minDuration: Duration,
    @JsonProperty("MaxDuration")
    @field:Valid
    val maxDuration: Duration
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var minDuration: Duration? = null,
        private var maxDuration: Duration? = null
    ) {
        fun minDuration(minDuration: Duration) = apply { this.minDuration = minDuration }

        fun maxDuration(maxDuration: Duration) = apply { this.maxDuration = maxDuration }

        fun build(): RentalLimits {
            // Check required params
            validateNullity()
            return RentalLimits(
                minDuration = minDuration!!,
                maxDuration = maxDuration!!
            )
        }

        private fun validateNullity() {
            if (minDuration == null) {
                throw NullPointerException("Required parameter minDuration is missing")
            }
            if (maxDuration == null) {
                throw NullPointerException("Required parameter maxDuration is missing")
            }
        }
    }

    fun toBuilder() =
        Builder(
            minDuration = minDuration!!,
            maxDuration = maxDuration!!
        )
}
