/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.xap.models

import com.expediagroup.sdk.xap.models.RatePlanStandalonePriceAvgNightlyRate
import com.expediagroup.sdk.xap.models.RatePlanStandalonePriceBaseRate
import com.expediagroup.sdk.xap.models.RatePlanStandalonePriceHotelMandatoryFees
import com.expediagroup.sdk.xap.models.RatePlanStandalonePriceTaxesAndFees
import com.expediagroup.sdk.xap.models.RoomTypeStandalonePriceTotalPrice
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * The corresponded standalone price to the package rate plan (to show the `strikethrough`). Only returned when this is a package rate plan.
 * @param baseRate
 * @param taxesAndFees
 * @param totalPrice
 * @param avgNightlyRate
 * @param hotelMandatoryFees
 */
data class RoomTypeStandalonePrice(
    @JsonProperty("BaseRate")
    @field:Valid
    val baseRate: RatePlanStandalonePriceBaseRate? = null,
    @JsonProperty("TaxesAndFees")
    @field:Valid
    val taxesAndFees: RatePlanStandalonePriceTaxesAndFees? = null,
    @JsonProperty("TotalPrice")
    @field:Valid
    val totalPrice: RoomTypeStandalonePriceTotalPrice? = null,
    @JsonProperty("AvgNightlyRate")
    @field:Valid
    val avgNightlyRate: RatePlanStandalonePriceAvgNightlyRate? = null,
    @JsonProperty("HotelMandatoryFees")
    @field:Valid
    val hotelMandatoryFees: RatePlanStandalonePriceHotelMandatoryFees? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var baseRate: RatePlanStandalonePriceBaseRate? = null,
        private var taxesAndFees: RatePlanStandalonePriceTaxesAndFees? = null,
        private var totalPrice: RoomTypeStandalonePriceTotalPrice? = null,
        private var avgNightlyRate: RatePlanStandalonePriceAvgNightlyRate? = null,
        private var hotelMandatoryFees: RatePlanStandalonePriceHotelMandatoryFees? = null
    ) {
        fun baseRate(baseRate: RatePlanStandalonePriceBaseRate?) = apply { this.baseRate = baseRate }

        fun taxesAndFees(taxesAndFees: RatePlanStandalonePriceTaxesAndFees?) = apply { this.taxesAndFees = taxesAndFees }

        fun totalPrice(totalPrice: RoomTypeStandalonePriceTotalPrice?) = apply { this.totalPrice = totalPrice }

        fun avgNightlyRate(avgNightlyRate: RatePlanStandalonePriceAvgNightlyRate?) = apply { this.avgNightlyRate = avgNightlyRate }

        fun hotelMandatoryFees(hotelMandatoryFees: RatePlanStandalonePriceHotelMandatoryFees?) = apply { this.hotelMandatoryFees = hotelMandatoryFees }

        fun build(): RoomTypeStandalonePrice {
            return RoomTypeStandalonePrice(
                baseRate = baseRate,
                taxesAndFees = taxesAndFees,
                totalPrice = totalPrice,
                avgNightlyRate = avgNightlyRate,
                hotelMandatoryFees = hotelMandatoryFees
            )
        }
    }

    fun toBuilder() =
        Builder(
            baseRate = baseRate,
            taxesAndFees = taxesAndFees,
            totalPrice = totalPrice,
            avgNightlyRate = avgNightlyRate,
            hotelMandatoryFees = hotelMandatoryFees
        )
}
