/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.xap.models

import com.expediagroup.sdk.xap.models.CarMoney
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * List of TaxesAndFees Details
 * @param description TaxesAndFees description
 * @param amount
 */
data class TaxesAndFees(
    // TaxesAndFees description
    @JsonProperty("Description")
    @field:Valid
    val description: kotlin.String,
    @JsonProperty("Amount")
    @field:Valid
    val amount: CarMoney
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var description: kotlin.String? = null,
        private var amount: CarMoney? = null
    ) {
        fun description(description: kotlin.String) = apply { this.description = description }

        fun amount(amount: CarMoney) = apply { this.amount = amount }

        fun build(): TaxesAndFees {
            // Check required params
            validateNullity()
            return TaxesAndFees(
                description = description!!,
                amount = amount!!
            )
        }

        private fun validateNullity() {
            if (description == null) {
                throw NullPointerException("Required parameter description is missing")
            }
            if (amount == null) {
                throw NullPointerException("Required parameter amount is missing")
            }
        }
    }

    fun toBuilder() =
        Builder(
            description = description!!,
            amount = amount!!
        )
}
