name: Generate
on:
  workflow_call:
    inputs:
      version:
        description: 'generated sdk version'
        required: true
        type: string
      name:
        description: 'generated sdk name'
        required: true
        type: string
      fileAsBase64:
        description: 'generated sdk file as base64 encoded'
        required: true
        type: string
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: build
        run: mvn clean install
      - name: generate
        working-directory: openapi
        run: |
          mvn clean install
          mvn exec:java "-Dnamespace=${{ inputs.name }}" -DsdkVersion=${{ inputs.version }} "-Dspec=${{ inputs.fileAsBase64 }}"
      - uses: actions/upload-artifact@v3
        with:
          name: sdk
          path: ./openapi/target/sdk
