name: Build & Test SDK
on:
  pull_request:
    branches:
      - 'main'
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  generate-sdk:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: build-with-maven
        run: mvn clean install
      - name: Generate SDK Files
        working-directory: ./openapi
        run: |
          mvn clean install
          mvn exec:java "-Dnamespace=exemplar" "-DsdkVersion=0.0.1-exemplar" "-Dspec=${{ secrets.SPEC_FILE }}"
      - uses: actions/upload-artifact@v2
        with:
          name: sdk
          path: ./openapi/target/sdk
  verify-generated-sdk:
    runs-on: macos-latest
    needs: generate-sdk
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sdk
          path: sdk
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: verify generated sdk
        working-directory: ./sdk
        run: mvn verify