name: Publish
on:
  workflow_call:
    inputs:
      test:
        description: 'Release snapshot?'
        required: false
jobs:
  job:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.version }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sdk
          path: sdk
      - name: "JDK set-up"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: oss-sonatype # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: SONATYPE_USERNAME # env variable for username in deploy
          server-password: SONATYPE_PASSWORD # env variable for token in deploy
          # only signed artifacts will be released to maven central. this sets up things for the maven-gpg-plugin
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
          settings-path: ${{ github.workspace }}
      - name: "Release artifacts"
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
        run: |
          cd sdk
          if [ -z "${{ github.event.inputs.test }}" ]; then
            mvn deploy --settings $GITHUB_WORKSPACE/settings.xml -B -U -P release -DskipTests=true
          else
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            SNAPSHOT_VERSION="${VERSION%-SNAPSHOT}-SNAPSHOT"
            mvn deploy --settings $GITHUB_WORKSPACE/settings.xml -B -U -P release -DskipTests=true -Drevision=$SNAPSHOT_VERSION
          fi
          echo "{version}=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
