/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.rapid.models.Link
import com.expediagroup.sdk.rapid.operations.DeleteHeldBookingOperationLink
import com.expediagroup.sdk.rapid.operations.GetReservationByItineraryIdOperationLink
import com.expediagroup.sdk.rapid.operations.PutResumeBookingOperationLink
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * A map of links, including links to retrieve a booking, resume a held booking, or cancel a held booking.
 * @param retrieve
 * @param resume
 * @param cancel
 */
data class CompletePaymentSessionLinks(
    @JsonProperty("retrieve")
    @field:Valid
    val retrieve: GetReservationByItineraryIdOperationLink? = null,
    @JsonProperty("resume")
    @field:Valid
    val resume: PutResumeBookingOperationLink? = null,
    @JsonProperty("cancel")
    @field:Valid
    val cancel: DeleteHeldBookingOperationLink? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var retrieve: GetReservationByItineraryIdOperationLink? = null,
        private var resume: PutResumeBookingOperationLink? = null,
        private var cancel: DeleteHeldBookingOperationLink? = null
    ) {
        fun retrieve(retrieve: GetReservationByItineraryIdOperationLink?) = apply { this.retrieve = retrieve }

        fun resume(resume: PutResumeBookingOperationLink?) = apply { this.resume = resume }

        fun cancel(cancel: DeleteHeldBookingOperationLink?) = apply { this.cancel = cancel }

        fun build(): CompletePaymentSessionLinks {
            return CompletePaymentSessionLinks(
                retrieve = retrieve,
                resume = resume,
                cancel = cancel
            )
        }
    }
}
