/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.rapid.models.Link
import com.expediagroup.sdk.rapid.operations.GetAdditionalAvailabilityOperationLink
import com.expediagroup.sdk.rapid.operations.GetAvailabilityOperationLink
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * A map of links, including links to request additional rates. Note that the recommendations feature has been retired and will return an error if the link is followed.
 * @param additionalRates
 * @param recommendations
 */
data class PropertyAvailabilityLinks(
    @JsonProperty("additional_rates")
    @field:Valid
    val additionalRates: GetAdditionalAvailabilityOperationLink? = null,
    @JsonProperty("recommendations")
    @field:Valid
    val recommendations: GetAvailabilityOperationLink? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var additionalRates: GetAdditionalAvailabilityOperationLink? = null,
        private var recommendations: GetAvailabilityOperationLink? = null
    ) {
        fun additionalRates(additionalRates: GetAdditionalAvailabilityOperationLink?) = apply { this.additionalRates = additionalRates }

        fun recommendations(recommendations: GetAvailabilityOperationLink?) = apply { this.recommendations = recommendations }

        fun build(): PropertyAvailabilityLinks {
            return PropertyAvailabilityLinks(
                additionalRates = additionalRates,
                recommendations = recommendations
            )
        }
    }
}
