name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test-core-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test Core Packages
        run: ./gradlew clean build

  build-and-test-exemplar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test Exemplar
        run: |
          cd exemplar && ./gradlew clean build

