name: Close and Release Sonatype Staging

on:
  push:
    branches:
      - "mdwairi/configure-publish-tasks"

jobs:
  close-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Close Staging Repository
        run: |
          curl -u "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" \
               -X POST \
               -H "Content-Type: application/json" \
               -d '{
                     "data": {
                       "stagedRepositoryIds": [ "comexpediagroup-1674" ],
                       "description": "Close staging repo via REST API"
                     }
                   }' \
               "https://s01.oss.sonatype.org/service/local/staging/bulk/close"

