name: CodeCov
on:
  pull_request:
    types: [opened, reopened]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
