name: Verify Core
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  verify-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "JDK set-up"
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: verify core
        working-directory: core
        run: mvn verify -P github-verify-action-profile
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Upload coverage reports to Codecov
        run: |
          pip install codecov-cli
          codecovcli upload-process -t ${{ secrets.CODECOV_TOKEN }}

