name: Verify Core
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  verify-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "JDK set-up"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: verify core
        working-directory: core
        run: mvn verify -P github-verify-action-profile
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
