name: Drop Sonatype Staging Repository

on:
  workflow_dispatch:



jobs:
  drop-staging-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Drop staging repository
        run: |
          curl -u "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" \
               -X POST \
               -H "Content-Type: application/json" \
               -d '{
                     "data": {
                       "stagedRepositoryIds": [
                         "comexpediagroup-1674"
                       ],
                       "description": "Dropping this staging repository via REST API."
                     }
                   }' \
               "https://oss.sonatype.org/service/local/staging/bulk/drop"
