name: Verify generated SDK
on:
  pull_request:
    branches:
      - 'main'
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - id: build-with-maven
        working-directory: generator
        run: mvn clean install -P github-generate-action-profile
      - name: Generate SDK Files
        working-directory: generator/openapi
        run: |
          mvn clean install
          mvn exec:java -Dnamespace=exemplar "-DsdkVersion=1.0.0" "-Dspec=./src/test/resources/exemplar.yaml"
      - uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: generator/openapi/target/sdk
  verify-generated-sdk:
    runs-on: ubuntu-latest
    needs: generate-sdk
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: sdk
          from-job: generate-sdk
          path: generator/openapi/target/sdk
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: verify generated sdk
        working-directory: generator/openapi/target/sdk
        run: mvn verify
