name: Generate SDK - Main
on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
      endpoint_prefix:
        description: 'Endpoint to prepend specs paths with'
        required: true
        type: string
      specs_url:
        description: 'URL to download API specs from'
        required: true
        type: string
      production_release:
        description: 'Release to production'
        required: true
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      name:
        description: 'SDK Name'
        required: true
      version:
        description: 'SDK Version'
        required: true
      endpoint_prefix:
        description: 'Endpoint to prepend specs paths with'
        required: true
        type: string
      specs_url:
        description: 'URL to download API specs from'
        required: true
        type: string
      production_release:
        description: 'Release to production'
        required: true
        type: boolean
        default: false

jobs:
  print_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "SDK Name: ${{ inputs.name }}"
          echo "SDK Version: ${{ inputs.version }}"
          echo "Endpoint Prefix: ${{ inputs.endpoint_prefix }}"
          echo "Specs URL: ${{ inputs.specs_url }}"
          echo "Production Release: ${{ inputs.production_release }}"
  download_specs:
    uses: ./.github/workflows/generator-download-specs.yaml
    with:
      url: ${{ inputs.specs_url }}
  transform_specs:
    needs: [ download_specs ]
    uses: ./.github/workflows/generator-transform-specs.yaml
    with:
      configurations: -th -te ${{ inputs.endpoint_prefix }} --operationIdsToTags
  generate:
    needs: [ transform_specs ]
    uses: ./.github/workflows/generator-generate.yaml
    with:
      name: ${{ inputs.name }}
      version: ${{ inputs.version }}
  publish_sources:
    needs: [ generate ]
    uses: ./.github/workflows/generator-publish-sources.yaml
    with:
      name: ${{ inputs.name }}
      version: ${{ inputs.version }}
  publish_artifact:
    needs: [ generate ]
    uses: ./.github/workflows/generator-publish-artifact.yaml
    secrets: inherit
    with:
      production_release: ${{ inputs.production_release == 'true' }}
  draft_release:
    if: ${{ inputs.production_release == 'true' }}
    needs: [ generate ]
    secrets: inherit
    uses: ./.github/workflows/generator-draft-release.yaml
