name: Generate Test SDK
on:
  workflow_call:
    inputs:
      version:
        description: 'SDK version to generate test jar for'
        required: true
        type: string
      namespace:
        description: 'SDK to generate test jar for'
        required: true
        type: string
      endpoint_prefix:
        description: 'Endpoint to prepend specs paths with'
        required: true
        type: string
      specs_url:
        description: 'Run tests based on specs'
        required: true
        type: string
    outputs:
      artifactId:
        value: ${{ jobs.sdk-metadata.outputs.artifactId }}
      groupId:
        value: ${{ jobs.sdk-metadata.outputs.groupId }}
      version:
        value: ${{ jobs.sdk-metadata.outputs.version }}

jobs:
  download-specs:
    uses: ./.github/workflows/generator-download-specs.yaml
    with:
      url: ${{ inputs.specs_url }}
  transform-specs:
    needs: [ download-specs ]
    uses: ./.github/workflows/selfserve-transform-specs.yaml
    with:
      specs_key: 'raw-specs'
      transformations: -th -te ${{ inputs.endpoint_prefix }} --operationIdsToTags
  generate-sdk:
    needs: [ transform-specs ]
    uses: ./.github/workflows/selfserve-generate.yaml
    with:
      templates: 'sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk'
      name: ${{ inputs.namespace }}
      version: ${{ inputs.version }}
