name: Publish Release
on:
  workflow_dispatch:
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Prepare tags
        run: |
          chmod +x ./get-latest-tag.sh
          latest=$(./get-latest-tag.sh)
          echo "Latest tag is $latest"
          git config --system --unset credential.helper
#          git config --list
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/osama-salman99/expediagroup-java-sdk
          git tag v1.0.0 $latest
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
      - name: Install dependencies
        run: npm install
      - name: Create draft release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

