name: Generate SDK - Generate
on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - id: build
        working-directory: generator
        run: mvn clean install
      - id: build-processor
        working-directory: generator/openapi/src/main/resources/post-processor
        run: npm ci && npm run clean && npm run build
      - uses: actions/download-artifact@v4
        with:
          name: specs
          path: generator/openapi
      - name: generate
        working-directory: generator/openapi
        run: |
          mvn clean install exec:java "-Dnamespace=${{ inputs.name }}" -DsdkVersion=${{ inputs.version }} "-Dspec=./specs.yaml"
      - name: test
        working-directory: generator/openapi
        run: |
          npm run --prefix src/main/resources/post-processor process target/sdk/src/main/kotlin/com/expediagroup/sdk/xap/models/HotelPolicies.kt
      - name: install sdk
        working-directory: generator/openapi/target/sdk
        run: |
          mvn clean install
      - uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: |
            generator/openapi/target/sdk
            !generator/openapi/target/sdk/target
          overwrite: true
      - uses: actions/upload-artifact@v4
        with:
          name: jar
          path: |
            generator/openapi/target/sdk/target/*.jar
            generator/openapi/target/sdk/target/maven-archiver/pom.properties
          overwrite: true
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: generator/openapi/target/sdk/target/dokka
          overwrite: true
