name: Generate and Publish Sources
on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
      production_release:
        description: 'Release to Production? (yes/no)'
        type: string
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sdk
          path: generator/sdk
      - uses: actions/download-artifact@v3
        with:
          name: specs
          path: generator/sdk
      - name: Add generated source code
        working-directory: generator/sdk
        if: ${{ "${{github.event.inputs.production_release}}" == "yes"}}
        run: |
          rm -rf ../../release/"${{github.event.inputs.name}}"
          mkdir -p ../../release/"${{github.event.inputs.name}}"
          cp -r ./src ../../release/"${{github.event.inputs.name}}"/
          cp ./pom.xml ../../release/"${{github.event.inputs.name}}"/
          cp ./README.md ../../release/"${{github.event.inputs.name}}"/
          cp ./specs.yaml ../../release/"${{github.event.inputs.name}}"/specs.yaml
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "${{github.event.inputs.name}}-${{github.event.inputs.version}}"
          commit-message: "chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK"
          title: "chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK"
          path: ./release

