name: Generate Contract Tests
on:
  workflow_call:
    inputs:
      specs_url:
        description: 'URL to download API specs from'
        required: true
        type: string
      endpoint_prefix:
        description: 'Endpoint to prepend specs paths with'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      specs_url:
        description: 'URL to download API specs from'
        required: true
        type: string
      endpoint_prefix:
        description: 'Endpoint to prepend specs paths with'
        required: true
        type: string
jobs:
  download_specs:
    uses: ./.github/workflows/generator-download-specs.yaml
    with:
      url: ${{ github.event.inputs.specs_url }}
  transform_specs:
    needs: [ download_specs ]
    uses: ./.github/workflows/generator-transform-specs.yaml
    with:
      configurations: -th -te ${{ github.event.inputs.endpoint_prefix }} --operationIdsToTags --oneOf
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: specs
          path: sdk-test
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate Contract Tests
        working-directory: sdk-test
        run:
          mkdir -p contract-tests
          output=$(realpath ./contract-tests)
          mvn clean install exec:java -Dexec.args="-i specs.yaml -o $output"
      - uses: actions/upload-artifact@v4
        with:
          name: contract-tests
          path: contract-tests
