name: Download API Specs
on:
  workflow_call:
    inputs:
      url:
        description: 'URL to download API specs from'
        required: true
        type: string

jobs:
  download_specs:
    runs-on: ubuntu-latest
    steps:
      - id: download_specs
        run: |
          curl -L ${{ inputs.url }} -o raw-specs.yaml
      - id: check_artifact_exists
        uses: LIT-Protocol/artifact-exists-action@v0
        with:
          name: raw-specs
      - uses: actions/upload-artifact@v4
        if: steps.check_artifact_exists.outputs.exists == 'false'
        with:
          name: raw-specs
          path: raw-specs.yaml
          overwrite: true
