name: Publish Release
on:
  workflow_dispatch:
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
      - name: Install dependencies
        run: npm install
      - name: Prepare tags
        run: |
          git fetch --tags
          tags=$(git tag -l "v*")
          latest_tag=$(echo "$tags" | grep -E '^v[0-9]+$' | sort -Vr | head -n 1)

          echo "Latest tag: $latest_tag"
          git tag v1.0.0 "$latest_tag"
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Create draft release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

