name: Publish Release
on:
  workflow_dispatch:
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Create tag
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/osama',
              sha: 'd91f62127859b50e806d2b858a1bcc04b47b6138'
            })
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
      - name: Install dependencies
        run: npm install
      - name: Create draft release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

