name: Run Tests
on: push

jobs: 
  run-rapid-tests-21:
    uses: ./.github/workflows/run-tests.yaml
    with:
      source: 'specs'
      specs_url: 'https://ewe-assets.s3.amazonaws.com/developer-tools/api/rapid/v3/specs.yaml'
      sdk_version: 1.0.${{ github.run_id }}
      sdk_namespace: 'rapid'
      jdk: 21
      endpoint_prefix: '/v3'