name: Run Tests
on:
  push:

jobs: 
  run-rapid-tests:
    strategy:
      matrix:
        jdk: [21, 17, 11, 8]
    uses: ./.github/workflows/run-tests.yaml
    with: 
      source: 'specs'
      specs_url: 'https://ewe-assets.s3.amazonaws.com/developer-tools/api/rapid/v3/specs.yaml'
      sdk_version: 1.0.${{ github.run_id }}
      sdk_namespace: 'rapid'
      jdk: ${{ matrix.jdk }}
      endpoint_prefix: '/v3'
