name: PR Check Tests Run
on: push

jobs:
  run-rapid-tests:
    uses: ./.github/workflows/run-tests.yaml
    with:
      sdk_version: 1.0.${{ github.run_id }}
      sdk_namespace: 'rapid'
      transformations: '-th -te /v3 --operationIdsToTags'
      product_repo: 'ExpediaGroup/rapid-java-sdk'
    secrets: inherit
