name: PR Check Tests Run
on: push

jobs:
  run-rapid-tests:
    uses: ./.github/workflows/run-tests.yaml
    with:
      source: 'specs'
      sdk_version: 1.0.${{ github.run_id }}
      product: 'rapid'
    secrets: inherit
