name: release-please

on:
  push:
    branches:
      - "mdwairi/configure-publish-tasks"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
    outputs:
      expediagroup-sdk-core--released: ${{ steps.release.outputs.expediagroup-sdk-core--release_created}}
      expediagroup-sdk-graphql--released: ${{ steps.release.outputs.expediagroup-sdk-graphql--release_created}}
      expediagroup-sdk-rest--released: ${{ steps.release.outputs.expediagroup-sdk-rest--release_created}}
      expediagroup-sdk-transport-okhttp--released: ${{ steps.release.outputs.expediagroup-sdk-transport-okhttp--release_created}}
      expediagroup-sdk-openapi-plugin--released: ${{ steps.release.outputs.expediagroup-sdk-openapi-plugin--release_created}}

  release-expediagroup-sdk-core:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.expediagroup-sdk-core--released}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Publish expediagroup-sdk-core
        run: ./gradlew :expediagroup-sdk-core:publishToMavenLocal

      - name: Print Maven Local contents
        run: ls -R ~/.m2/repository

