name: release-please

on:
  push:
    branches:
      - "feature/new-sdk-core"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
    outputs:
      expediagroup-sdk-core--released: ${{ steps.release.outputs.expediagroup-sdk-core--release_created}}
      expediagroup-sdk-graphql--released: ${{ steps.release.outputs.expediagroup-sdk-graphql--release_created}}
      expediagroup-sdk-rest--released: ${{ steps.release.outputs.expediagroup-sdk-rest--release_created}}
      expediagroup-sdk-transport-okhttp--released: ${{ steps.release.outputs.expediagroup-sdk-transport-okhttp--release_created}}
      expediagroup-sdk-openapi-plugin--released: ${{ steps.release.outputs.expediagroup-sdk-openapi-plugin--release_created}}

  release-expediagroup-sdk-core:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.expediagroup-sdk-core--released}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Publish expediagroup-sdk-core
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew :expediagroup-sdk-core:publish

  release-expediagroup-sdk-graphql:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.expediagroup-sdk-graphql--released}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Publish expediagroup-sdk-graphql
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew :expediagroup-sdk-graphql:publish

  release-expediagroup-sdk-rest:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.expediagroup-sdk-rest--released}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Publish expediagroup-sdk-rest
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew :expediagroup-sdk-rest:publish

  release-expediagroup-sdk-transport-okhttp:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.expediagroup-sdk-transport-okhttp--released}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Publish expediagroup-sdk-transport-okhttp
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew :expediagroup-sdk-transport-okhttp:publish

  release-expediagroup-sdk-openapi-plugin:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.expediagroup-sdk-openapi-plugin--released}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Publish expediagroup-sdk-openapi-plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

        run: ./gradlew :expediagroup-sdk-openapi-plugin:publishPlugins

