name: release-please

on:
  push:
    branches:
      - "feature/new-sdk-core"
      - "mdwairi/configure-publish-tasks"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      expediagroup-sdk-core--released: ${{ steps.release.outputs.expediagroup-sdk-core--release_created }}
      expediagroup-sdk-graphql--released: ${{ steps.release.outputs.expediagroup-sdk-graphql--release_created }}
      expediagroup-sdk-rest--released: ${{ steps.release.outputs.expediagroup-sdk-rest--release_created }}
      expediagroup-sdk-transport-okhttp--released: ${{ steps.release.outputs.expediagroup-sdk-transport-okhttp--release_created }}
      expediagroup-sdk-openapi-plugin--released: ${{ steps.release.outputs.expediagroup-sdk-openapi-plugin--release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  release:
    needs: release-please
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - expediagroup-sdk-core
          - expediagroup-sdk-graphql
          - expediagroup-sdk-rest
          - expediagroup-sdk-transport-okhttp
          - expediagroup-sdk-openapi-plugin
    if: ${{ needs.release-please.outputs[format('{0}--released', matrix.module) ] }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

#      - name: Publish ${{ matrix.module }}
#        env:
#          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
#          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#        run: |
#          ./gradlew :${{ matrix.module }}:publishToSonatype closeAndReleaseSonatypeStagingRepository
