name: Run Tests
on:
  push:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of tests'
        required: true
        type: string
        options:
          - 'specs'
          - 'sdk'
        default: 'sdk'
      specs_url:
        description: 'Run tests based on specs'
        required: false
        type: string
        default: ''
      sdk_version:
        description: 'Run tests based on SDK'
        required: false
        type: string
        default: 'LATEST'
      sdk_namespace:
        description: 'SDK to test'
        required: true
        type: string
        options:
          - rapid
        default: 'rapid'
      endpoint_prefix:
        description: 'Endpoint to prepend specs paths with'
        required: true
        type: string
      jdk:
        description: 'JDK version to use'
        required: true
        type: string
        options:
          - '17'
          - '21'
        default: '17'
  workflow_call:
    inputs:
      source:
        description: 'Source of tests'
        required: true
        type: string
        default: 'sdk'
      specs_url:
        description: 'Run tests based on specs'
        required: false
        type: string
        default: ''
      sdk_version:
        description: 'Run tests based on SDK'
        required: false
        type: string
        default: 'LATEST'
      sdk_namespace:
        description: 'SDK to test'
        required: true
        type: string
        default: 'rapid'
      jdk:
        description: 'JDK version to use'
        required: true
        type: string
        default: '17'
      endpoint_prefix:
        description: 'Endpoint to prepend specs paths with'
        required: true
        type: string

jobs:
  inputs-validation:
    runs-on: ubuntu-latest
    steps:
      - shell: python -u {0}
        run: |
          if any([
            'specs' in '${{ github.event.inputs.source }}' and not('${{ github.event.inputs.specs_url }}'),
            'sdk' in '${{ github.event.inputs.source }}' and not('${{ github.event.inputs.sdk_version }}')
          ]):
            print('::error::Invalid inputs')
            exit(1)
  download-specs:
    if: ${{ github.event.inputs.source == 'specs' }}
    needs: [ inputs-validation ]
    uses: ./.github/workflows/generator-download-specs.yaml
    with:
      url: ${{ github.event.inputs.specs_url }}
  transform-specs:
    if: ${{ github.event.inputs.source == 'specs' }}
    needs: [ download-specs, inputs-validation ]
    uses: ./.github/workflows/generator-transform-specs.yaml
    with:
      configurations: -th -te ${{ github.event.inputs.endpoint_prefix }} --operationIdsToTags
  generate-sdk:
    if: ${{ github.event.inputs.source == 'specs' }}
    needs: [ transform-specs, inputs-validation ]
    uses: ./.github/workflows/generator-generate.yaml
    with:
      name: ${{ github.event.inputs.sdk_namespace }}
      version: ${{ github.event.inputs.sdk_version }}
  do-echo:
    runs-on: ubuntu-latest
    needs: [ generate-sdk, inputs-validation ]
    steps:
      - run: |
          echo "${{ github.run_id }}"
  run-rapid-examples:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    needs: [ generate-sdk, inputs-validation ]
    uses: "ExpediaGroup/rapid-java-sdk/.github/workflows/run-examples.yaml@OmarAlJarrah/add-cli-execution-plugin"
    with:
      sdk_version: ${{ github.event.inputs.sdk_version }}
      jdk: ${{ github.event.inputs.jdk }}
      sdk_generation_workflow_run_id: ${{ github.run_id }}
    secrets:
      KEY: ${{ secrets.RAPID_KEY }}
      SECRET: ${{ secrets.RAPID_SECRET }}
