name: Upload Specs (from Repo)

on:
  workflow_call:
    inputs:
      repository:
        description: |
          Repository to download the artifact from.
          Leave empty to use the current repository.
        type: string
        default: ''
      ref:
        description: |
          Branch or tag to checkout.
          Leave empty to use the default branch.
        type: string
        default: ''
      artifact_key:
        description: 'Key to the artifact'
        type: string
        required: true
      artifact_path:
        description: 'Path to the artifact'
        type: string
        default: .

jobs:
  upload-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Upload specs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_key }}
          path: ${{ inputs.artifact_path }}
