name: Generate SDK

on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
      templates_key:
        description: 'Key to the combined templates artifact'
        required: true
        type: string
      specs_key:
        description: |
          Key to the transformed and ready to use specs artifact and name
          (without extension, e.g. specs, the file is expected to have the extension .yaml).
        default: 'transformedSpecs'
        type: string
      sdk_key:
        description: 'Key to the generated SDK artifact'
        default: 'sdk'
        type: string
      sdk_repo_key:
        description: 'Key to the SDK repository artifact'
        default: 'sdk-repo'
        type: string
      jar_key:
        description: 'Key to the generated JAR artifact'
        default: 'jar'
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Download SDK Repository
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.sdk_repo_key }}
          path: sdk-repo

      - name: Download Specs
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.specs_key }}

      - name: Download Templates
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.templates_key }}

      - name: Build Generator Post-processor
        working-directory: sdk-repo/generator/openapi/src/main/resources/post-processor
        run: npm ci && npm run clean && npm run build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Product SDK
        env:
          KOTLIN_POST_PROCESS_FILE: "npm run --prefix sdk-repo/generator/openapi/src/main/resources/post-processor process"
        run: |
          TEMPLATE_DIR= ./sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk/
          ls -la
          mvn -f sdk-repo/generator/openapi clean install exec:java "-Dnamespace=${{ inputs.name }}" -DsdkVersion=${{ inputs.version }} "-Dspec=./${{ inputs.specs_key }}.yaml" -DtemplatesDir=$TEMPLATE_DIR

      - name: Install SDK
        run: |
          mvn clean install -f sdk-repo/generator/openapi/target/sdk

      - name: Persist SDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.sdk_key }}
          path: |
            sdk-repo/generator/openapi/target/sdk
            !sdk-repo/generator/openapi/target/sdk/target

      - name: Persist JAR Artifact # TODO: Remove when product config is proposed
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.jar_key }}
          path: |
            sdk-repo/generator/openapi/target/sdk/target/*.jar
            sdk-repo/generator/openapi/target/sdk/target/maven-archiver/pom.properties
          overwrite: true
