name: Transform Specs
on:
  workflow_call:
    inputs:
      specs_key:
        description: 'Key to the specs artifact and name (without extension, e.g. specs, the file is expected to have the extension .yaml)'
        type: string
        default: 'specs'
      transformations:
        description: 'Spec Transformer CLI Configurations'
        type: string
        required: true
      transformed_specs_key:
        description: 'Key to the transformed specs artifact and name (without extension, e.g. transformedSpecs, the file is expected to have the extension .yaml)'
        type: string
        default: 'transformedSpecs'
      repository:
        description: 'Repository to checkout'
        type: string
        required: true
      ref:
        description: 'Branch or tag to checkout'
        type: string
        required: true

jobs:
  transform-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout product repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: product-repo

      - name: Transform specs
        working-directory: product-repo
        run: |
          npx --yes -p @expediagroup/spec-transformer cli ${{ inputs.transformations }} -i ${{ inputs.specs_key }}.yaml -o ${{ inputs.transformed_specs_key }}.yaml

      - name: Upload transformed specs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.transformed_specs_key }}
          path: product-repo/${{ inputs.transformed_specs_key }}.yaml
