name: Generate and Publish SDK (Full Workflow)

on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
      templates:
        description: 'Path to the templates directory'
        type: string
        default: 'sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk'
      specs_key:
        description: |
          Key to the transformed and ready to use specs artifact and name
          (without extension, e.g. specs, the file is expected to have the extension .yaml).
          The artifact is expected to be in the root of the repository.
        type: string
        default: 'specs'
      transformed_specs_key:
        description: |
          Key to the transformed specs artifact and name
          (without extension, e.g. transformedSpecs, the file is expected to have the extension .yaml).
        type: string
        default: 'transformedSpecs'
      transformations:
        description: 'Spec Transformer CLI Configurations'
        type: string
        default: '--headers --operationIdsToTags'
      sources_path:
        description: 'Path to publish the source code to. This should be a path of a directory where the source code will be published to'
        type: string
        default: 'code'


jobs:
  transform-specs:
    uses: ./.github/workflows/selfserve-transform-specs.yaml
    with:
      specs_key: ${{ inputs.specs_key }}
      transformations: ${{ inputs.transformations }}
      transformed_specs_key: ${{ inputs.transformed_specs_key }}
  generate-sdk:
    uses: ./.github/workflows/selfserve-generate.yaml
    needs: [ transform-specs ]
    with:
      name: ${{ inputs.name }}
      version: ${{ inputs.version }}
      templates: ${{ inputs.templates }}
      specs_key: ${{ inputs.transformed_specs_key }}
  publish-sources:
    uses: ./.github/workflows/selfserve-publish-sources.yaml
    needs: [ generate-sdk ]
    with:
      version: ${{ inputs.version }}
      path: ${{ inputs.sources_path }}
      specs_key: ${{ inputs.transformed_specs_key }}
  publish-sdk:
    uses: ./.github/workflows/selfserve-release.yaml
    needs: [ generate-sdk, publish-sources ]
