name: Generate SDK

on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
      sdk_key:
        description: 'Key to the generated SDK artifact'
        default: 'sdk'
        type: string
      jar_key:
        description: 'Key to the generated JAR artifact'
        default: 'jar'
        type: string
      sdk_repo_ref:
        description: |
          Branch or tag to checkout on the `expediagroup-sdk-core` repository.
          Leave empty to use the default branch (legacy).
        type: string
        default: 'legacy'
      repository:
        description: |
          Repository to generate the SDK in.
          Leave empty to use the current repository.
        type: string
        default: ''
      ref:
        description: |
          Branch or tag to checkout on the provided repository.
          Leave empty to use the default branch.
        type: string
        default: ''

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout generator repository
        uses: actions/checkout@v4
        with:
          repository: 'ExpediaGroup/expediagroup-java-sdk'
          ref: ${{ inputs.sdk_repo_ref }}
          path: sdk-repo

      - name: Checkout product repository
        uses: actions/checkout@v4
        with:
          repository:  ${{ inputs.repository }}
          ref:  ${{ inputs.ref }}
          path: product-repo

      - name: Download Specs
        uses: actions/download-artifact@v4
        with:
          name: transformedSpecs

      - name: Apply product customizations
        run: |
          cp -R product-repo/customizations/* sdk-repo

      - name: Build Generator Post-processor
        working-directory: sdk-repo/generator/openapi/src/main/resources/post-processor
        run: npm ci && npm run clean && npm run compile

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Product SDK
        env:
          KOTLIN_POST_PROCESS_FILE: "npm run --prefix sdk-repo/generator/openapi/src/main/resources/post-processor process"
        run: |
          mvn -f sdk-repo/generator/openapi clean install exec:java "-Dnamespace=${{ inputs.name }}" -DsdkVersion=${{ inputs.version }} "-Dspec=./transformedSpecs.yaml"

      - name: Install SDK
        run: |
          mvn clean install -f sdk-repo/generator/openapi/target/sdk

      - name: Persist SDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.sdk_key }}
          path: |
            sdk-repo/generator/openapi/target/sdk
            !sdk-repo/generator/openapi/target/sdk/target

      - name: Persist JAR Artifact # TODO: Remove when product config is proposed
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.jar_key }}
          path: |
            sdk-repo/generator/openapi/target/sdk/target/*.jar
            sdk-repo/generator/openapi/target/sdk/target/maven-archiver/pom.properties
          overwrite: true
