name: Release an SDK to Maven Central

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch to release the SDK from. Defaults to 'main'"
        type: string
        default: 'main'
      sdk_path:
        description: "Path to the SDK sources. Defaults to 'code'"
        type: string
        default: 'code'

jobs:
  release-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: oss-sonatype
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
          settings-path: ${{ github.workspace }}

      - name: Checkout SDK branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          path: product-repo

      - name: Release SDK
        working-directory: product-repo/${{ inputs.sdk_path }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
        run: |
          echo "Starting SDK Release - version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          mvn deploy --settings $GITHUB_WORKSPACE/settings.xml -B -U -P release -DskipTests=true
          echo "SDK Released"
