name: Generate SDK

on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
      templates:
        description: 'Path to the templates directory'
        required: true
        type: string
      specs_key:
        description: 'Key to the transformed and ready to use specs artifact and name (without extension, e.g. specs, the file is expected to have the extension .yaml)'
        default: 'specs'
        type: string
      sdk_key:
        description: 'Key to the generated SDK artifact'
        default: 'sdk'
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EG SDK Repository
        uses: actions/checkout@v4
        with:
          repository: 'ExpediaGroup/expediagroup-java-sdk'
          path: sdk-repo

      - name: Download Specs
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.specs_key }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Product SDK
        run: |
          mvn -f sdk-repo/generator/openapi clean install exec:java "-Dnamespace=${{ inputs.name }}" -DsdkVersion=${{ inputs.version }} "-Dspec=./${{ inputs.specs_key }}.yaml" -DtemplatesDir=./${{ inputs.templates }}

      - name: Install SDK
        working-directory: sdk-repo/generator/openapi/target/sdk
        run: |
          mvn clean install

      - name: Persist SDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.sdk_key }}
          path: |
            sdk-repo/generator/openapi/target/sdk
            !sdk-repo/generator/openapi/target/sdk/target
