name: Transform Specs
on:
  workflow_call:
    inputs:
      specs_key:
        description: 'Key to the specs artifact and name (without extension, e.g. specs, the file is expected to have the extension .yaml)'
        type: string
        default: 'specs'
      transformations:
        description: 'Spec Transformer CLI Configurations'
        type: string
        required: true
      transformed_specs_key:
        description: 'Key to the transformed specs artifact and name (without extension, e.g. transformedSpecs, the file is expected to have the extension .yaml)'
        type: string
        default: 'transformedSpecs'

jobs:
  transform-specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.specs_key }}

      - run: |
          npx --yes -p @expediagroup/spec-transformer cli ${{ inputs.transformations }} -i ${{ inputs.specs_key }}.yaml -o ${{ inputs.transformed_specs_key }}.yaml

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.transformed_specs_key }}
          path: ${{ inputs.transformed_specs_key }}.yaml
