name: Generate SDK

on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
      specs_key:
        description: 'Key to the specs artifact and name (without extension, e.g. specs, the file is expected to have the extension .yaml)'
        required: true
        type: string
      templates:
        description: 'Path to the templates directory'
        required: true
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'ExpediaGroup/expediagroup-java-sdk'
          path: sdk-repo

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.specs_key }}
          path: sdk-repo/generator/openapi

      - name: generate
        working-directory: sdk-repo/generator/openapi
        run: |
          mvn clean install exec:java "-Dnamespace=${{ inputs.name }}" -DsdkVersion=${{ inputs.version }} "-Dspec=./${{ inputs.specs_key }}.yaml" -DtemplatesDir="${{ inputs.templates }}"

      - name: install SDK
        working-directory: sdk-repo/generator/openapi/target/sdk
        run: |
          mvn clean install

      - uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: |
            sdk-repo/generator/openapi/target/sdk
            !sdk-repo/generator/openapi/target/sdk/target

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: sdk-repo/generator/openapi/target/sdk/target/dokka
