name: Generate and Publish SDK (Full Workflow)

on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: |
          SDK Version.
          E.g., 1.0.0, 1.0.1, 1.0.0-SNAPSHOT, etc.
        required: true
        type: string
      sdk_repo_ref:
        description: |
          Branch or tag to checkout on the `expediagroup-sdk-core` repository.
          Leave empty to use the default branch.
        type: string
        default: ''
      repository:
        description: |
          Repository to generate the SDK in.
          Leave empty to use the current repository.
        type: string
        default: ''
      ref:
        description: |
          Branch or tag to checkout on the provided repository.
          Leave empty to use the default branch.
        type: string
        default: ''
      transformations:
        description: 'Spec Transformer CLI Configurations'
        type: string
        default: '--headers --operationIdsToTags'
      sources_path:
        description: 'Path to publish the source code to. This should be a path of a directory where the source code will be published to'
        type: string
        default: 'code'
      sdk_key:
        description: |
          Key to the generated SDK artifact.
          This artifact will be generated by the generation job and used to publish the SDK.
        type: string
        default: 'sdk'

jobs:
  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "SDK Name: ${{ inputs.name }}"
          echo "SDK Version: ${{ inputs.version }}"
          echo "SDK Repository Ref: ${{ inputs.sdk_repo_ref }}"
          echo "Repository: ${{ inputs.repository }}"
          echo "Ref: ${{ inputs.ref }}"
          echo "Transformations: ${{ inputs.transformations }}"
          echo "Sources Path: ${{ inputs.sources_path }}"
          echo "SDK Key: ${{ inputs.sdk_key }}"
          echo "SDK Repository Key: ${{ inputs.sdk_repo_key }}"

  transform-specs:
    uses: ./.github/workflows/selfserve-transform-specs.yaml
    with:
      transformations: ${{ inputs.transformations }}
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}

  generate-sdk:
    uses: ./.github/workflows/selfserve-generate-sdk.yaml
    needs: [ transform-specs ]
    with:
      name: ${{ inputs.name }}
      version: ${{ inputs.version }}
      sdk_key: ${{ inputs.sdk_key }}
      sdk_repo_ref: ${{ inputs.sdk_repo_ref }}
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}

  publish-sources:
    uses: ./.github/workflows/selfserve-publish-sources.yaml
    needs: [ generate-sdk ]
    with:
      version: ${{ inputs.version }}
      path: ${{ inputs.sources_path }}
      sdk_key: ${{ inputs.sdk_key }}

  release-sdk:
    uses: ./.github/workflows/selfserve-release-sdk.yaml
    needs: [ generate-sdk ]
    secrets: inherit
    with:
      sdk_key: ${{ inputs.sdk_key }}
