name: Generate and Publish SDK (Full Workflow)

on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: |
          SDK Version.
          E.g., 1.0.0, 1.0.1, 1.0.0-SNAPSHOT, etc.
        required: true
        type: string
      templates:
        description: |
          Path to the templates directory.
          Use the default path if you are using the default templates.
          Use `sdk-repo` to refer to the `expediagroup-sdk` repo root path if needed.
        type: string
        default: 'sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk'
      repo:
        description: |
          Repository to generate the SDK in.
          Leave empty to use the current repository.
        type: string
        default: ''
      ref:
        description: |
          Branch or tag to checkout.
          Leave empty to use the default branch.
        type: string
        default: ''
      specs_key:
        description: |
          Key to the OpenAPI specs artifact and name
          (without extension, e.g. specs, the file is expected to have the extension .yaml).
          The artifact is expected to be in the root of the repository, unless you specify a different path
          using the specs_path input.
        type: string
        default: 'specs'
      specs_path:
        description: 'Path to the specs file in the provided repository'
        type: string
        default: 'specs.yaml'
      transformed_specs_key:
        description: |
          Key to the transformed specs artifact and name.
          (without extension, e.g. transformedSpecs, the file is expected to have the extension .yaml).
          This artifact will be generated by the transformation job and used to generate the SDK.
          This artifact will be published with this name into the provided sources_path directory.
        type: string
        default: 'transformedSpecs'
      transformations:
        description: 'Spec Transformer CLI Configurations'
        type: string
        default: '--headers --operationIdsToTags'
      sources_path:
        description: 'Path to publish the source code to. This should be a path of a directory where the source code will be published to'
        type: string
        default: 'code'
      sdk_key:
        description: |
          Key to the generated SDK artifact.
          This artifact will be generated by the generation job and used to publish the SDK.
        type: string
        default: 'sdk'


jobs:
  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "SDK Name: ${{ inputs.name }}"
          echo "SDK Version: ${{ inputs.version }}"
          echo "Templates: ${{ inputs.templates }}"
          echo "Repository: ${{ inputs.repo }}"
          echo "Ref: ${{ inputs.ref }}"
          echo "Specs Key: ${{ inputs.specs_key }}"
          echo "Specs Path: ${{ inputs.specs_path }}"
          echo "Transformed Specs Key: ${{ inputs.transformed_specs_key }}"
          echo "Transformations: ${{ inputs.transformations }}"
          echo "Sources Path: ${{ inputs.sources_path }}"
          echo "SDK Key: ${{ inputs.sdk_key }}"

  upload-specs:
    uses: ./.github/workflows/selfserve-upload-specs.yaml
    with:
      specs_key: ${{ inputs.specs_key }}
      specs_path: ${{ inputs.specs_path }}
      repository: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}

  transform-specs:
    uses: ./.github/workflows/selfserve-transform-specs.yaml
    needs: [ upload-specs ]
    with:
      specs_key: ${{ inputs.specs_key }}
      transformations: ${{ inputs.transformations }}
      transformed_specs_key: ${{ inputs.transformed_specs_key }}

  generate-sdk:
    uses: ./.github/workflows/selfserve-generate.yaml
    needs: [ transform-specs ]
    with:
      name: ${{ inputs.name }}
      version: ${{ inputs.version }}
      templates: ${{ inputs.templates }}
      specs_key: ${{ inputs.transformed_specs_key }}
      sdk_key: ${{ inputs.sdk_key }}

  publish-sources:
    uses: ./.github/workflows/selfserve-publish-sources.yaml
    needs: [ generate-sdk ]
    with:
      version: ${{ inputs.version }}
      path: ${{ inputs.sources_path }}
      sdk_key: ${{ inputs.sdk_key }}
      specs_key: ${{ inputs.transformed_specs_key }}

  release:
    uses: ./.github/workflows/selfserve-release.yaml
    needs: [ generate-sdk, publish-sources ]
    with:
      sdk_key: ${{ inputs.sdk_key }}
