name: Generate and Publish Sources

on:
  workflow_call:
    inputs:
      version:
        description: 'SDK Version - A semantic SDK version, e.g., 1.0.0 or 1.0.0-SNAPSHOT'
        required: true
        type: string
      path:
        description: 'Path to publish the source code to'
        required: true
        type: string
      sdk_key:
        description: 'Key to the generated SDK artifact'
        default: 'sdk'
        type: string
      specs_key:
        description: 'Key to the transformed and ready to publish specs artifact and name (without extension, e.g. specs, the file is expected to have the extension .yaml)'
        default: 'tspecs'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.sdk_key }}
          path: sdk-repo/generator/${{ inputs.sdk_key }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.specs_key }}
          path: .
      - name: Add generated source code to the path
        run: |
          rm -rf ${{ inputs.path }}
          mkdir -p ${{ inputs.path }}

          echo "${{ inputs.specs_key }}"
          ls -la -R

          cp -r ./sdk-repo/generator/sdk/src ${{ inputs.path }}/src
          cp ./sdk-repo/generator/sdk/pom.xml ${{ inputs.path }}/src
          cp ./sdk-repo/generator/sdk/README.md ${{ inputs.path }}/src
          cp ./${{ inputs.specs_key }}.yaml ${{ inputs.path }}/${{ inputs.specs_key }}.yaml

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "publish-v${{ inputs.version }}"
          commit-message: "chore: Publish v${{ inputs.version }}"
          title: "chore: Publish v${{ inputs.version }}"
          add-paths: |
            ${{ inputs.path }}/*
