name: Upload Specs (from Repo)

on:
  workflow_call:
    inputs:
      repository:
        description: |
          Repository to download the specs from.
          Leave empty to use the current repository.
        type: string
        default: ''
      ref:
        description: |
          Branch or tag to checkout.
          Leave empty to use the default branch.
        type: string
        default: ''
      specs_key:
        description: 'Key to the specs artifact'
        type: string
        default: 'specs'
      specs_path:
        description: 'Path to the specs file'
        type: string
        default: 'specs.yaml'

jobs:
  upload-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Upload specs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.specs_key }}
          path: ${{ inputs.specs_path }}
