name: Generate and Publish Sources

on:
  workflow_call:
    inputs:
      version:
        description: 'SDK Version - A semantic SDK version, e.g., 1.0.0 or 1.0.0-SNAPSHOT'
        required: true
        type: string
      branch:
        description: |
          Branch to publish the source code to and create the PR from.
          Defaults to "publish-v<<version>>"
        default: ''
        type: string
      path:
        description: 'Path to publish the source code to. This should be a path of a directory where the source code will be published to'
        default: 'code'
        type: string
      sdk_key:
        description: 'Key to the generated SDK artifact'
        default: 'sdk'
        type: string
      sdk_repo_key:
        description: 'Key to the SDK repository artifact'
        default: 'sdk-repo'
        type: string

jobs:
  publish-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch
        run: |
          if [ -z "${{ inputs.branch }}" ]; then
              echo "branch=publish-v${{ inputs.version }}" >> $GITHUB_ENV
          else
              echo "branch=${{ inputs.branch }}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.sdk_key }}
          path: ${{ inputs.sdk_repo_key }}/${{ inputs.sdk_key }}

      - uses: actions/download-artifact@v4
        with:
          name: transformedSpecs
          path: .

      - name: Add generated source code to the path
        run: |
          rm -rf ${{ inputs.path }}
          mkdir -p ${{ inputs.path }}

          cp -r ${{ inputs.sdk_repo_key }}/${{ inputs.sdk_key }}/src ${{ inputs.path }}/src
          cp ${{ inputs.sdk_repo_key }}/${{ inputs.sdk_key }}/pom.xml ${{ inputs.path }}
          cp ${{ inputs.sdk_repo_key }}/${{ inputs.sdk_key }}/README.md ${{ inputs.path }}
          cp ${{ inputs.sdk_repo_key }}/${{ inputs.sdk_key }}/LICENSE-HEADER.txt ${{ inputs.path }}
          cp ./${{ inputs.specs_key }}.yaml ${{ inputs.path }}/${{ inputs.specs_key }}.yaml

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ env.branch }}
          commit-message: "chore: Publish v${{ inputs.version }}"
          title: "chore: Publish v${{ inputs.version }}"
          body: |
            This PR publishes the source code for `v${{ inputs.version }}` in the `${{ inputs.path }}` directory.
            Generated by the EG SDK generator.
          add-paths: |
            ${{ inputs.path }}/*
